title: 3 Seconds
description: The Ultimate Guide to the Front Cover of Books
footer_text: Copyright 2021 Freya Nelder-Hunt
header_feature_image: ../uploads/pages.jpg
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: ../uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
