title: 3 Seconds
description: The Ultimate Guide to the Front Cover of Books
footer_text: Copyright 2021 Freya Nelder-Hunt
header_feature_image: ../uploads/log.jpg
header_text: The ultimate guide to making successful book covers
header_text_color: "#ffffff"
bannerheight: 50vmax
logo: ../uploads/logo.jpg
favicon: ../uploads/goldenratio.png
gridlayout: true
fixednavbar: true
upzoom: true
